print("Enter input string")
a=str(input())
print("String is",a)
print("Returned postion",a[0])
b=a.capitalize()
print("Capitalize first letter",b)
B=a.casefold()
print("Lower case",B)
c=a.replace("Hello","Zamorin")
print("Replaced to :",c)
splt=a.split()
print("Splitted Strings",splt)